'use strict';
const D=window.REPORT_DATA, $=id=>document.getElementById(id), money=n=>n==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n/100), fmt=n=>n==null?'—':n.toLocaleString('en-US'), pct=n=>n==null?'—':(n*100).toFixed(1)+'%', esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let selected=[], page=0;
const refunds=new Map();D.refunds.forEach(r=>{const k=[r.channel,r.order_id,r.line_id].join('|');refunds.set(k,(refunds.get(k)||0)+r.refund_cents)});
const key=r=>[r.channel,r.order_id,r.line_id].join('|'), order=r=>[r.channel,r.order_id].join('|'), refund=r=>refunds.get(key(r))||0;
function stats(rs){const os=new Set(rs.map(order)), positive=new Set(rs.filter(r=>refund(r)>0).map(order)), returning=new Set(rs.filter(r=>r.customer_type==='Returning').map(order)), s=rs.reduce((s,r)=>s+r.sales_cents,0), f=rs.reduce((s,r)=>s+refund(r),0);return[s,f,s-f,os.size,os.size?s/os.size:null,os.size?positive.size/os.size:null,os.size?returning.size/os.size:null]}
function shift(s,n){const d=new Date(s+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function ranges(){const p=$('period').value;if(p==='custom'){const a=$('from').value,b=$('to').value;if(!a||!b||a>b)return null;const days=(new Date(b)-new Date(a))/864e5+1;return[a,b,shift(a,-days),shift(a,-1)]}if(p==='q3')return['2025-07-01','2025-09-30','2025-04-01','2025-06-30'];const n=Number(p),a=`2025-${p}-01`,end=new Date(Date.UTC(2025,n,0)).toISOString().slice(0,10),prev=new Date(Date.UTC(2025,n-2,1)).toISOString().slice(0,10);return[a,end,prev,shift(a,-1)]}
function filtered(a,b){return D.rows.filter(r=>r.order_date>=a&&r.order_date<=b&&['channel','country','category'].every(k=>!$(k).value||r[k]===$(k).value))}
const palette=['#1e3a8a','#f59e0b','#0f766e','#91a9de','#c9d4e8'];const charts={};['trend','channels','categories','countries','sources','customers'].forEach(id=>charts[id]=echarts.init($(id),null,{renderer:'svg'}));
function base(){return{color:palette,animation:false,tooltip:{trigger:'axis'},grid:{left:55,right:12,top:25,bottom:35},textStyle:{fontFamily:'Segoe UI, Arial',color:'#58677e',fontSize:11}}}
function groups(rs,k){const g={};rs.forEach(r=>{g[r[k]]=(g[r[k]]||0)+r.sales_cents/100});return Object.entries(g).sort((a,b)=>b[1]-a[1])}
function draw(rs,a,b){const dates=[];for(let d=a;d<=b&&dates.length<370;d=shift(d,1))dates.push(d);const buckets=new Map(dates.map(d=>[d,[]]));rs.forEach(r=>buckets.get(r.order_date)?.push(r));const daily=dates.map(d=>stats(buckets.get(d)));charts.trend.setOption({...base(),legend:{bottom:0,data:['Sales','Net sales']},xAxis:{type:'category',data:dates.map(d=>d.slice(5)),boundaryGap:false},yAxis:{type:'value',axisLabel:{formatter:v=>'$'+(v>=1000?(v/1000).toFixed(1)+'k':v)},splitLine:{lineStyle:{color:'#edf1f7'}}},series:[{name:'Sales',type:'line',data:daily.map(s=>s[0]/100),showSymbol:false,smooth:.25,lineStyle:{width:3},areaStyle:{opacity:.07}},{name:'Net sales',type:'line',data:daily.map(s=>s[2]/100),showSymbol:false,smooth:.25,lineStyle:{width:2,type:'dashed'}}]},true);
const ch=groups(rs,'channel');charts.channels.setOption({color:palette,animation:false,tooltip:{trigger:'item',formatter:'{b}: ${c} ({d}%)'},legend:{bottom:0,textStyle:{fontSize:11}},series:[{type:'pie',radius:['48%','72%'],center:['50%','43%'],label:{show:false},data:ch.map(([name,value])=>({name,value:Math.round(value*100)/100}))}]},true);
for(const [id,k] of [['categories','category'],['countries','country']]){const g=groups(rs,k).reverse();charts[id].setOption({...base(),grid:{left:70,right:18,top:15,bottom:25},xAxis:{type:'value',axisLabel:{formatter:v=>v>=1000?'$'+Math.round(v/1000)+'k':'$'+v}},yAxis:{type:'category',data:g.map(r=>r[0])},series:[{type:'bar',barMaxWidth:20,data:g.map(r=>r[1]),itemStyle:{color:id==='countries'?'#0f766e':'#1e3a8a',borderRadius:[0,4,4,0]}}]},true)}
const sg={};new Map(rs.map(r=>[order(r),r])).forEach(r=>sg[r.traffic_source]=(sg[r.traffic_source]||0)+1);charts.sources.setOption({...base(),grid:{left:90,right:15,top:15,bottom:25},xAxis:{type:'value',minInterval:1},yAxis:{type:'category',data:Object.keys(sg)},series:[{type:'bar',data:Object.values(sg),barMaxWidth:18,itemStyle:{color:'#f59e0b',borderRadius:[0,4,4,0]}}]},true);
charts.customers.setOption({...base(),legend:{bottom:0,data:['New orders','Returning orders','Returning share']},xAxis:{type:'category',data:dates.map(d=>d.slice(5))},yAxis:[{type:'value',minInterval:1},{type:'value',min:0,max:100,axisLabel:{formatter:'{value}%'}}],series:[{name:'New orders',type:'bar',stack:'orders',data:daily.map(s=>s[3]-(s[6]||0)*s[3])},{name:'Returning orders',type:'bar',stack:'orders',data:daily.map(s=>(s[6]||0)*s[3])},{name:'Returning share',type:'line',yAxisIndex:1,showSymbol:false,data:daily.map(s=>s[6]==null?null:s[6]*100),itemStyle:{color:'#0f766e'}}]},true)}
function renderTable(){const pages=Math.max(1,Math.ceil(selected.length/30));page=Math.min(page,pages-1);$('rows').innerHTML=selected.slice(page*30,(page+1)*30).map(r=>`<tr><td>${r.order_date}</td><td>${r.channel}</td><td>${esc(r.order_id)} / ${esc(r.line_id)}</td><td>${esc(r.product_name)}</td><td>${r.country}</td><td>${r.quantity}</td><td>${money(r.sales_cents)}</td><td>${money(refund(r))}</td><td>${money(r.sales_cents-refund(r))}</td></tr>`).join('');$('detail-count').textContent=fmt(selected.length)+' valid lines · 30 per page';$('page-info').textContent=`Page ${page+1} of ${pages}`;$('prev').disabled=page===0;$('next').disabled=page===pages-1}
function update(){const range=ranges();if(!range){$('range-note').textContent='Choose a valid start and end date.';selected=[];$('metrics').innerHTML='';$('empty').hidden=false;Object.values(charts).forEach(c=>c.clear());renderTable();return}const[a,b,pa,pb]=range,complete=pa>=D.coverage[0]&&pb<=D.coverage[1];selected=filtered(a,b);const s=stats(selected),p=complete?stats(filtered(pa,pb)):null;$('range-note').textContent=`${a} – ${b} · ${complete?'vs '+pa+' – '+pb:'Comparison unavailable: baseline outside data coverage'}${$('category').value?' · AOV includes selected category merchandise only':''}`;$('empty').hidden=selected.length>0;
const labels=['Sales','Refunds','Net sales','Orders','Average order value','Refund order rate'];$('metrics').innerHTML=labels.map((label,i)=>{let comparison='Baseline unavailable';if(p){if(i===5)comparison=s[i]==null||p[i]==null?'Not comparable: no orders':((s[i]-p[i])*100>=0?'+':'')+((s[i]-p[i])*100).toFixed(1)+' pp vs previous period';else comparison=s[i]==null||p[i]==null?'Not comparable: no orders':p[i]===0?'Not comparable: zero baseline':((s[i]-p[i])/p[i]*100>=0?'+':'')+((s[i]-p[i])/p[i]*100).toFixed(1)+'% vs previous period'}return`<article class="metric ${i===2?'featured':''}"><div class="metric-label">${label}</div><div class="metric-value">${i===3?fmt(s[i]):i===5?pct(s[i]):money(s[i])}</div><div class="comparison">${comparison}</div></article>`}).join('');draw(selected,a,b);renderTable()}
['period','channel','country','category','from','to'].forEach(id=>$(id).addEventListener('change',()=>{$('custom-dates').hidden=$('period').value!=='custom';page=0;$('download-csv').hidden=true;$('export-status').textContent='';update()}));$('reset').onclick=()=>{['channel','country','category'].forEach(id=>$(id).value='');$('period').value='09';$('from').value='2025-09-01';$('to').value='2025-09-30';$('custom-dates').hidden=true;page=0;update()};$('prev').onclick=()=>{page--;renderTable()};$('next').onclick=()=>{page++;renderTable()};$('export').onclick=()=>{const fields=['order_date','channel','order_id','line_id','product_name','category','country','quantity','sales_usd','refunds_usd','net_sales_usd','source_file','source_row'];const quote=s=>'"'+String(s).replace(/"/g,'""')+'"';const csv=[fields,...selected.map(r=>[r.order_date,r.channel,r.order_id,r.line_id,r.product_name,r.category,r.country,r.quantity,(r.sales_cents/100).toFixed(2),(refund(r)/100).toFixed(2),((r.sales_cents-refund(r))/100).toFixed(2),r.source_file,r.source_row])].map(row=>row.map(quote).join(',')).join('\r\n');const url='data:text/csv;charset=utf-8,'+encodeURIComponent('\ufeff'+csv);const link=$('download-csv');if(link.href.startsWith('blob:'))URL.revokeObjectURL(link.href);link.href=url;link.download='nestora-filtered-sales.csv';link.hidden=false;$('export-status').textContent=selected.length+' lines prepared for download.';link.click()};
$('generated').textContent='Generated '+new Date(D.generated).toLocaleString('en-GB');$('quality-counts').innerHTML=['orders','products','refunds'].map(k=>`<div><strong>${k[0].toUpperCase()+k.slice(1)}</strong>✓ ${fmt(D.quality[k].retained||0)} retained<br>↻ ${fmt(D.quality[k].deduplicated||0)} deduplicated<br>! ${fmt(D.quality[k].pending||0)} pending</div>`).join('')+`<p>${D.quality.excluded_orders} whole orders excluded. Quality counts cover the entire input, independently of sales filters.</p>`;$('exceptions').innerHTML=D.exceptions.map(r=>`<tr><td>${r.kind}</td><td>${esc(r.file)} : ${r.row}</td><td>${r.status}</td><td>${esc(r.reason)}</td><td>${esc(JSON.stringify(r.original))}</td></tr>`).join('');window.addEventListener('resize',()=>Object.values(charts).forEach(c=>c.resize()));update();
